version: "3.9"
services:  
  ig2-nginx:    
    container_name: ig2-nginx
    image: nginx:1.21.6-alpine
    ports:      
      - 80:80
      - 443:443
    volumes:      
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/filancore:/etc/ssl/private:ro
  waltid-backend:    
    container_name: waltid-backend
    image: waltid/idpkit
    ports:
      - 8080
    environment:
      - WALTID_DATA_ROOT=/data 
    volumes:      
      - ./:/data
    command:      
      - run
  waltid-ui:    
    container_name: waltid-ui
    image: waltid/idpkit-ui
    ports:      
      - 8080:80